name: Checks
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests with Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: npm install
    - run: npx hardhat test
      env:
        # These are not needed for the tests but
        # hardhat fails to start if not present.
        NODE_TEST: "x"
        NODE_MAIN: "x"
        PRIVATE_KEY: "00000000000000000000000000000000000000000000000000"
        REPORT_GAS: "true"
  Linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Solhint
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm install -g solhint
      - run: make solhint
  Security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Echidna Mutating testing
        run: |
          pip install crytic-compile slither-analyzer
          wget https://github.com/crytic/echidna/releases/download/v1.7.0/echidna-test-1.7.0-Ubuntu-18.04.zip
          unzip echidna-test-1.7.0-Ubuntu-18.04.zip
          tar -xf echidna-test.tar.gz
          mv ./echidna-test /usr/bin/
          echidna-test . --contract ChorusTest
        env:
          # These are not needed for the tests but
          # slither runs hardhat to compile the contracts and
          # hardhat compilation fails if these are not present.
          NODE_TEST: "x"
          NODE_MAIN: "x"
          PRIVATE_KEY: "00000000000000000000000000000000000000000000000000"
